// export const ADD_TO_CART=  "ADD_TO_CART"
// export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
// export const CHANGE_CART_QTY = "CHANGE_CART_QTY"


export const ADD_ITEM_TO_CART_REQUEST = "ADD_ITEM_TO_CART_REQUEST";
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS";
export const ADD_ITEM_TO_CART_FAIL = "ADD_ITEM_TO_CART_FAIL";

export const REMOVE_ITEM_FROM_CART_REQUEST = "REMOVE_ITEM_FROM_CART_REQUEST";
export const REMOVE_ITEM_FROM_CART_SUCCESS = "REMOVE_ITEM_FROM_CART_SUCCESS";
export const REMOVE_ITEM_FROM_CART_FAIL = "REMOVE_ITEM_FROM_CART_FAIL";

export const UPDATE_CART_ITEM_QTY_REQUEST = "UPDATE_CART_ITEM_QTY_REQUEST";
export const UPDATE_CART_ITEM_QTY_SUCCESS = "UPDATE_CART_ITEM_QTY_SUCCESS";
export const UPDATE_CART_ITEM_QTY_FAIL = "UPDATE_CART_ITEM_QTY_FAIL";





export const SORT_BY_PRICE = "SORT_BY_PRICE"
export const FILTER_BY_STOCK = "FILTER_BY_PRICE"
export const FILTER_BY_DELIVERY = "FILTER_BY_DELIVERY"
export const FILTER_BY_RATING = "FILTER_BY_RATING"
export const FILTER_BY_DISCOUNT= "FILTER_BY_DISCOUNT"
export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH"
export const CLEAR_FILTERS = "CLEAR_FILTERS"

